dubbo:
  application:
    name: spring-boot-dubbo-demo-consumer
  registry:
    address: multicast://224.5.6.7:1234
  protocol:
      name: dubbo
      port: 20888

spring:
  output:
    ansi:
      enabled: always