server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://www.aaa.com:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true

logging:
    level:
        java.sql: debug
        com.xxx.sample.spring.cloud: debug

spring:
    application:
      name: scs-producer-cas    # 项目名称尽量用小写
    cloud:
      config:
        discovery:
          enabled: true
          serviceId: SAMPLE-CONFIG

    datasource:
        name: spring-cloud-study
        url: jdbc:mysql://192.168.1.231:33060/spring-cloud-study?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    messages:
      encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
          map-underscore-to-camel-case: true
          default-fetch-size: 100
          default-statement-timeout: 30
  type-aliases-package: com.xxx.sample.spring.cloud.model

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql