server:
  port: 8000

logging:
    level:
        java.sql: debug
        com.xxx.sample.spring.cloud: debug

spring:
  messages:
    encoding: UTF-8
  output:
    ansi:
      enabled: always


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
          map-underscore-to-camel-case: true
          default-fetch-size: 100
          default-statement-timeout: 30
  type-aliases-package: com.xxx.sample.spring.cloud.model

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql