spring:
  application:
    name: scs-api-gateway
  output:
    ansi:
      enabled: always
server:
  port: 9998
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://www.aaa.com:8761/eureka/