

server:
  port: 10001
  context-path: /authclient

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      access-token-uri: http://localhost:10000/authserver/oauth/token
      user-authorization-uri: http://localhost:10000/authserver/oauth/authorize
    resource:
      user-info-uri: http://localhost:10000/authserver/user

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG