server:
  port: 9999
spring:
  application:
    name: scs-config-server-eureka
  output:
    ansi:
      enabled: always
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangorrin/spring-cloud/      # 配置git仓库的地址
          search-paths: spring-cloud-study/scs-config-repo      # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号
          password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://www.aaa.com:8761/eureka/